FROM centos

MAINTAINER janak.dudhrejiya@gmail.com

RUN yum -y install initscripts && yum clean all
RUN yum install libaio -y
RUN yum install numactl -y
RUN yum install perl -y
RUN mkdir /eClinicalWorks
WORKDIR /eClinicalWorks
RUN mkdir prodapps
WORKDIR /eClinicalWorks/prodapps
RUN mkdir mysql
WORKDIR /eClinicalWorks/prodapps/mysql
RUN mkdir mysql_binlogs
RUN mkdir tmp
COPY mysql /eClinicalWorks/prodapps/mysql
RUN groupadd mysql
RUN useradd -r -g mysql -s /bin/false mysql
RUN chown -R mysql.mysql /eClinicalWorks/prodapps/mysql
RUN chmod -R 755 /eClinicalWorks/prodapps/mysql
COPY my.cnf /etc
WORKDIR /eClinicalWorks/prodapps/mysql
RUN scripts/mysql_install_db --user=mysql --defaults-file=/etc/my.cnf
WORKDIR /eClinicalWorks/prodapps/mysql/support-files
RUN cp mysql.server /etc/init.d/mysqld
RUN chmod +x /etc/init.d/mysqld
EXPOSE 4928
CMD service mysqld start